name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t 1hari11111111/mtp
    - name: login
      run: docker login -u 1hari11111111 -p hari813143 && docker push 1hari11111111/mtp
