name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t tonystarkmahesh/hari:aeon
    - name: login
      run: docker login -u tonystarkmahesh -p SNEHITHA@2008 && docker push tonystarkmahesh/hari:aeon
